"""remove views_count from posts

Revision ID: 539272dbfb46
Revises: 609cd368f3d9
Create Date: 2026-05-09 10:36:58.923114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539272dbfb46'
down_revision: Union[str, Sequence[str], None] = '609cd368f3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_column('posts', 'views_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False))
   
    # ### end Alembic commands ###
