"""add views_count and post_likes

Revision ID: 609cd368f3d9
Revises: 2123c21f4c75
Create Date: 2026-05-08 15:33:28.283916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609cd368f3d9'
down_revision: Union[str, Sequence[str], None] = '2123c21f4c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_like')
    )
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=True))
    op.execute('UPDATE posts SET views_count = 0 WHERE views_count IS NULL')
    op.alter_column('posts', 'views_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    op.drop_column('posts', 'views_count')
    # ### end Alembic commands ###
